# Generated by Django 4.1.3 on 2023-01-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='hiddenname',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
