# Generated by Django 4.1.3 on 2023-01-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_types_hiddenname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='stock.stock'),
        ),
    ]
