# Generated by Django 4.1.3 on 2023-01-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='end',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='start',
            field=models.DateField(default=None),
        ),
    ]
